<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Option config file does not exist.' => 'Soubor s nastavením konfigurace neexistuje.',
    'Option type {type} not found' => 'Typ konfigurace {type} nebyl nalezen',
    'Save' => 'Uložit',
    'Invalid data type for option item {name}.' => 'Neplatný typ dat pro položku konfigurace {name}.',
    'Option config group have to be an array.' => 'Skupina konfigurace musí být pole.',
    'Option config group items have to be an array.' => 'Položky skupiny konfigurace musí být pole.',
    'Option config group title must be set.' => 'Název skupiny konfigurace musí být definován.',
    'Option config item name must be set.' => 'Název položky konfigurace musí být definován.',
    'Option config item title must be set.' => 'Titulek položky konfigurace musí být definován.',
    'Option config item type must be set.' => 'Typ položky konfigurace musí být definován.',
    'Option with name {name} is defined as context option but no context was specified.' => 'Položka konfigurace s názvem {name} je definována jako kontextová, ale kontext nebyl určen.',
    'Option with name {name} not defined.' => 'Položka konfigurace s názvem {name} není definována.',
    'Options' => 'Možnosti',
    'Successfully saved.' => 'Úspěšně uloženo.',
];
